web: add support of internatialization (#11)
i-core/werther pull request #16
Opened 2020-11-17 08:04 UTC by nikolaas

# Proposed Changes

The PR adds support for the internationalization of the login page.

2020-11-18 11:48 UTC, konstlepa requested changes

2020-11-18 11:48 UTC, konstlepa commented on internal/web/web.go
> +func isOldStyleUserTemplate(root *template.Template) bool {
Mention the issue that causes the creation of this function.

2020-11-18 11:48 UTC, konstlepa commented on internal/web/web.go
> +	if isOldStyleUserTemplate(root) {
Mention that this code will be deprecated in the future major release.

2020-11-18 11:48 UTC, konstlepa commented on internal/web/web_test.go
>  func TestHTMLRenderer(t *testing.T) {
Merge functions TestHTMLRender and TestHTMLRenderer_old_template.

2021-01-12 20:39 UTC, nikolaas commented on internal/web/web.go
> +func isOldStyleUserTemplate(root *template.Template) bool {
Done

2021-01-12 20:39 UTC, nikolaas commented on internal/web/web.go
> +	if isOldStyleUserTemplate(root) {
Done

2021-01-12 20:39 UTC, nikolaas commented on internal/web/web_test.go
>  func TestHTMLRenderer(t *testing.T) {
Done

2021-02-16 12:45 UTC, konstlepa requested changes

2021-02-16 12:45 UTC, konstlepa commented on internal/web/web_test.go
>  func TestHTMLRenderer(t *testing.T) {
Remove the dead code.

2021-03-05 15:24 UTC, merged