identp: Fake TLS termination
i-core/werther pull request #20
Opened 2021-05-13 05:51 UTC by Asherslab

## Proposed Changes

  - Adds FAKE_TLS_TERMINATION configuration variable
  - When configuration variable is enable requests to the hydra admin include the `X-Forwarded-Proto: http` header to fake TLS termination
  - This follows the similar implementation in the hydra CLI client: <https://github.com/ory/hydra/blob/24f91ab7038e4c612db5af86ff0f3ee5eb03c878/cmd/clients.go#L36>
  
## Use Case

 - Helps in situations where your installation has TLS termination (e.g. reverse proxy) and your werther installation is behind that proxy. such as kubernetes or docker installations.
  
  Please note that i am not a golang dev and am sorry for any errors in style/etc.

2021-08-05 07:20 UTC, nikolaas commented on internal/hydra/consent.go
> +	fakeTlsTermination bool
fakeTLSTermination

2021-08-05 07:34 UTC, nikolaas requested changes
Hello. Thank you for the PR. Great job! There are some fixes to a successful build

2021-08-05 07:34 UTC, nikolaas commented on internal/hydra/consent.go
> +func NewConsentReqDoer(hydraURL string, fakeTlsTermination bool, rememberFor int) *ConsentReqDoer {
replace fakeTlsTermination with fakeTLSTermination

2021-08-05 07:34 UTC, nikolaas commented on internal/hydra/hydra.go
> +func initiateRequest(typ reqType, hydraURL string, fakeTlsTermination bool, challenge string) (*ReqInfo, error) {
replace fakeTlsTermination with fakeTLSTermination

2021-08-05 07:34 UTC, nikolaas commented on internal/hydra/hydra.go
> +func acceptRequest(typ reqType, hydraURL string, fakeTlsTermination bool, challenge string, data interface{}) (string, error) {
replace fakeTlsTermination with fakeTLSTermination

2021-08-05 07:34 UTC, nikolaas commented on internal/hydra/login.go
> +	fakeTlsTermination bool
replace fakeTlsTermination with fakeTLSTermination

2021-08-05 07:34 UTC, nikolaas commented on internal/hydra/login.go
> +func NewLoginReqDoer(hydraURL string, fakeTlsTermination bool, rememberFor int) *LoginReqDoer {
replace fakeTlsTermination with fakeTLSTermination

2021-08-05 07:34 UTC, nikolaas commented on internal/hydra/logout.go
> +	fakeTlsTermination bool
replace fakeTlsTermination with fakeTLSTermination

2021-08-05 07:34 UTC, nikolaas commented on internal/hydra/logout.go
> +func NewLogoutReqDoer(hydraURL string, fakeTlsTermination bool) *LogoutReqDoer {
replace fakeTlsTermination with fakeTLSTermination

2021-08-05 07:34 UTC, nikolaas commented on internal/hydra/consent.go
> +	fakeTlsTermination bool
replace fakeTlsTermination with fakeTLSTermination

2021-08-05 07:35 UTC, nikolaas requested changes

2021-08-05 07:35 UTC, nikolaas commented on internal/identp/identp.go
> +	apply(http.MethodGet, "/logout", newLogoutHandler(hydra.NewLogoutReqDoer(h.HydraURL, h.FakeTLSTermination)))
Besides this, you have to fix tests because of the new argument in hydra.NewLoginReqDoer, hydra.NewConsentReqDoer, and hydra.NewLogoutReqDoer. Also, you need to add tests for fakeTLSTermination.

2021-08-06 12:41 UTC, Asherslab commented
Made changes for the above, 
however frankly i don't use go and thus don't have the experience in go to write new tests for the fakeTLSTermination.

2021-08-09 09:40 UTC, merged

2021-08-09 09:41 UTC, nikolaas commented
@ Asherslab, ok. Thank you for your work. I will add tests on my own.