map roles claim to single list
i-core/werther pull request #23
Opened 2022-09-26 08:05 UTC by cshazi

Fixes #14

## Proposed Changes

- You can map groups to roles claim using with the environment variable WERTHER_LDAP_FLAT_ROLE_CLAIMS

2022-09-27 00:33 UTC, nikolaas commented
Hello!

Thanks for the PR.

There is one thing that I would change. You make the Werther's configuration depending on data in LDAP by adding variable *WERTHER_LDAP_FLAT_ROLE_CLAIMS*. If data (an app name) will be changed it's needed to restart Werther.

There is another problem. Variable *WERTHER_LDAP_ROLE_CLAIM* provides the roles claim name (by default "https://github.com/i-core/werther/claims/roles"). But that is not enough for Werther's work. Also it is needed to map the roles claim name to the OpenId Connect scope "roles". Variable *WERTHER_OIDC_CLAIM_SCOPES* is for that. When WERTHER_LDAP_FLAT_ROLE_CLAIMS is defined we also have claims like "https://github.com/i-core/werther/claims/roles/app1" (the name may be arbitrary) and they are also must be mapped to the OpenId Connect scope "roles" via WERTHER_OIDC_CLAIM_SCOPES. Otherwise Werther won't provide this claims to the Hydra.


Lets make *WERTHER_LDAP_FLAT_ROLE_CLAIMS* boolean. When it is true Werther must add corresponding claims for all the apps.

Example 1:

```
WERTHER_LDAP_FLAT_ROLE_CLAIMS=false
```
```json
{
    "https://github.com/i-core/werther/claims/roles": {
        "App1": ["role1", "role2"],
        "App2": ["role3", "role4"],
    }
}
```

Example 2:

```
WERTHER_LDAP_FLAT_ROLE_CLAIMS=true
```
```json
{
    "https://github.com/i-core/werther/claims/roles": {
        "App1": ["role1", "role2"],
        "App2": ["role3", "role4"],
    },
    "https://github.com/i-core/werther/claims/roles/App1": ["role1", "role2"],
    "https://github.com/i-core/werther/claims/roles/App2": ["role3", "role4"],
}
```

***Note***. Besides editing *ldapclient.go* it is needed to modify the logic of claim filtration into *identp.go*. I want setting ***WERTHER_LDAP_FLAT_ROLE_CLAIMS=true*** not to force users to additionally map flatten role claims to the OpenId Connect scope "roles" via variable *WERTHER_OIDC_CLAIM_SCOPES*. In other words users should not do this:

2022-10-02 14:14 UTC, cshazi commented
Hello!

I have simplified the parameterization according to your comment.

2022-10-10 08:10 UTC, nikolaas requested changes

2022-10-10 08:10 UTC, nikolaas commented on cmd/werther/main.go
> +	RoleClaim string `envconfig:"role_claim" default:"https://github.com/i-core/werther/claims/roles" desc:"a name of an OpenID Connect claim that contains user roles"`
This is a breaking change. Lets try to avoid it.

For example, you can change the signature of oidcClaimsFinder to something like this:

```golang
type oidcClaimsFinder interface {
	FindOIDCClaims(ctx context.Context, username string) ([]Claim, error)
}

type Claim interface {
    Code string       // the root claim name
    Name string       // the claim name
    Value interface{} // the value
}
```

and then in the consent handler filter claims by the field "Code".

2022-10-17 11:21 UTC, cshazi commented on cmd/werther/main.go
> +	RoleClaim string `envconfig:"role_claim" default:"https://github.com/i-core/werther/claims/roles" desc:"a name of an OpenID Connect claim that contains user roles"`
done

2022-10-19 07:35 UTC, nikolaas requested changes

2022-10-19 07:35 UTC, nikolaas commented on internal/ldapclient/ldapclient.go
>  		if err = json.Unmarshal(cdata, &claims); err != nil {
Does it work? You changed the type of the variable `claims` from `map` to `slice` but JSON-data returned from ldap is the same as the previous (a JSON-object).

2022-10-19 07:35 UTC, nikolaas commented on internal/ldapclient/ldapclient.go
> +	if len(roles) > 0 {
This is also a breaking change. Before this change, claims always contained a claim with the name `cli.RoleClaim`. The value always was a map(empty or not). Now claims contain the claim only if its value is not an empty map.

Could you please get back the previous behavior?

2022-10-19 15:40 UTC, cshazi commented on internal/ldapclient/ldapclient.go
> +	if len(roles) > 0 {
Fixed, sorry.

2022-10-19 15:46 UTC, cshazi commented on internal/ldapclient/ldapclient.go
>  		if err = json.Unmarshal(cdata, &claims); err != nil {
In my opinion, yes. The `claims` variable is stored in the cache at the end of the method. The result of the ldap call is placed in the `entries` variable.

2022-10-19 15:54 UTC, nikolaas commented on internal/ldapclient/ldapclient.go
>  		if err = json.Unmarshal(cdata, &claims); err != nil {
Ок, I didn't notice

2022-10-19 15:57 UTC, nikolaas approved these changes

2022-10-19 15:58 UTC, merged

2022-10-19 15:58 UTC, nikolaas commented
That's ok. Thank you!